spring:
  application:
    name: checkout

inventory-service:
  baseUrl: ${INVENTORY_SERVICE_BASE_URL}
  reservePath: /reserve

order-service:
  baseUrl: ${ORDER_SERVICE_BASE_URL}
  createOrderPath: /orders

---
Spring:
  config:
    activate:
      on-profile: ["test", "local", "docker"]

  cloud:
    aws:
      region:
        static: "eu-central-1"
      credentials:
        access-key: "local_access_key"
        secret-key: "local_secret_key"
      endpoint: "http://localhost:4566"
      commerceEventsQueueUrl: "http://sqs.eu-central-1.localhost.localstack.cloud:4566/000000000000/commerce_events.fifo"

---
Spring:
  config:
    activate:
      on-profile: ["test", "local"]

inventory-service:
  baseUrl: "inventory-service"

order-service:
  baseUrl: "order-service"