spring:
  application.name: orders

  db:
    name: "orders"
    host: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  datasource:
    url: "jdbc:postgresql://${spring.db.host}:5432/${spring.db.name}"
    username: ${spring.db.username}
    password: ${spring.db.password}
  sql:
    init:
      platform: postgresql

  flyway:
    enabled: true
    url: "jdbc:postgresql://${spring.db.host}:5432/${spring.db.name}"
    user: ${spring.db.username}
    password: ${spring.db.password}

aws-resources:
  commerceEventsQueueUrl: ${AWS_COMMERCE_EVENTS_QUEUE_URL}


---
spring:
  config:
    activate:
      on-profile: ["test", "local", "docker"]
  cloud:
    aws:
      region:
        static: "eu-central-1"
      credentials:
        access-key: "local_access_key"
        secret-key: "local_secret_key"

---
spring:
  config:
   activate:
     on-profile: ["test", "local"]
  db:
   host: "localhost"
   username: "postgres"
   password: "password"

  cloud:
    aws:
      endpoint: "http://localhost:4566"

aws-resources:
  commerceEventsQueueUrl: "http://sqs.eu-central-1.localhost.localstack.cloud:4566/000000000000/commerce_events.fifo"

---
spring:
  config:
   activate:
     on-profile: ["docker"]
  cloud:
    aws:
      endpoint: "http://localstack:4566"
aws-resources:
  commerceEventsQueueUrl: "http://sqs.eu-central-1.localhost.localstack.cloud:4566/000000000000/commerce_events.fifo"